# This script was written by Kelsey Witt Dillon in April 2021. It processes
# genome coverage tables generated by "archaic_mp_cvg_ss.py" and other scripts
# from the same manuscript/project that generate *Nind_100x.csv files. This 
# (admittedly clunky) R code combines # the files into a single data table of 
# mean values and plots how archaic genome coverage changes with
# increasing sample size. As written, the code will run in Rstudio.

afr <- "#F2B900"   
amr <- "firebrick3"
eur <- "mediumblue"
sas <- "mediumorchid4"
eas <- "forestgreen"

color_vals <- c(rep(eas,5), rep(eur,5), rep(amr,4), rep(sas,5))
samples <- c("1", "5", "10", "25", "50", "75", "100", "125", "150")

coverage_1 <- read.csv("arch_all_mp_cvg_1ind_100x.csv", header = TRUE, sep = ",")
coverage_1$ss = "1"
coverage_1_melt <- melt(data = coverage_1, id.vars = c("run", "ss"), measure.vars = pops)
coverage_1_melt_names <- rename(coverage_1_melt,pop = variable,alleleCt = value)
coverage_5 <- read.csv("arch_all_mp_cvg_5ind_100x.csv", header = TRUE, sep = ",")
coverage_5$ss = "5"
coverage_5_melt <- melt(data = coverage_5, id.vars = c("run", "ss"), measure.vars = pops)
coverage_5_melt_names <- rename(coverage_5_melt,pop = variable,alleleCt = value)
coverage_10 <- read.csv("arch_all_mp_cvg_10ind_100x.csv", header = TRUE, sep = ",")
coverage_10$ss = "10"
coverage_10_melt <- melt(data = coverage_10, id.vars = c("run", "ss"), measure.vars = pops)
coverage_10_melt_names <- rename(coverage_10_melt,pop = variable,alleleCt = value)
coverage_25 <- read.csv("arch_all_mp_cvg_25ind_100x.csv", header = TRUE, sep = ",")
coverage_25$ss = "25"
coverage_25_melt <- melt(data = coverage_25, id.vars = c("run", "ss"), measure.vars = pops)
coverage_25_melt_names <- rename(coverage_25_melt,pop = variable,alleleCt = value)
coverage_50 <- read.csv("arch_all_mp_cvg_50ind_100x.csv", header = TRUE, sep = ",")
coverage_50$ss = "50"
coverage_50_melt <- melt(data = coverage_50, id.vars = c("run", "ss"), measure.vars = pops)
coverage_50_melt_names <- rename(coverage_50_melt,pop = variable,alleleCt = value)
coverage_75 <- read.csv("arch_all_mp_cvg_75ind_100x.csv", header = TRUE, sep = ",")
coverage_75$ss = "75"
coverage_75_melt <- melt(data = coverage_75, id.vars = c("run", "ss"), measure.vars = pops)
coverage_75_melt_names <- rename(coverage_75_melt,pop = variable,alleleCt = value)
coverage_100 <- read.csv("arch_all_mp_cvg_100ind_100x.csv", header = TRUE, sep = ",")
coverage_100$ss = "100"
coverage_100_melt <- melt(data = coverage_100, id.vars = c("run", "ss"), measure.vars = pops)
coverage_100_melt_names <- rename(coverage_100_melt,pop = variable,alleleCt = value)
coverage_125 <- read.csv("arch_all_mp_cvg_125ind_100x.csv", header = TRUE, sep = ",")
coverage_125$ss = "125"
coverage_125_melt <- melt(data = coverage_125, id.vars = c("run", "ss"), measure.vars = pops)
coverage_125_melt_names <- rename(coverage_125_melt,pop = variable,alleleCt = value)
coverage_150 <- read.csv("arch_all_mp_cvg_150ind_100x.csv", header = TRUE, sep = ",")
coverage_150$ss = "150"
coverage_150_melt <- melt(data = coverage_150, id.vars = c("run", "ss"), measure.vars = pops)
coverage_150_melt_names <- rename(coverage_150_melt,pop = variable,alleleCt = value)

all_coverage = bind_rows(coverage_1_melt_names,coverage_10_melt_names,coverage_25_melt_names,coverage_50_melt_names,coverage_75_melt_names,coverage_100_melt_names,coverage_125_melt_names,coverage_150_melt_names)
all_coverage$pop <- factor(all_coverage$pop, levels = pops)
all_coverage$ss <-factor(all_coverage$ss, levels = samples)
all_coverage_mean <- aggregate(all_coverage$alleleCt,list(pop=all_coverage$pop,ss=all_coverage$ss),mean)

ggplot(data = all_coverage_mean,aes(x=ss, y=x, color=pop))+
  geom_line(aes(group=pop))+
  geom_point(aes(shape=pop))+
  scale_color_manual(values=color_vals)+
  scale_shape_manual(values=c(0,1,2,8,6,0,1,2,8,6,0,1,2,8,0,1,2,8,6))+
  theme_classic()+ylab("Archaic Ancestry Coverage")+xlab("Sample Size")+
  theme(text = element_text(size = 14))+
  scale_size(guide='none')+guides(color=guide_legend(title="Population"),shape=guide_legend(title="Population"))
